database:
  arguments: host=localhost port=5432 user=postgres password=passwor dbname=postgres sslmode=disable
  type: postgres
telegram: 6153835213:AAEuLzqGtuuAjnvWVtDUxZhC1Hb5wa5VSs8

admins:
  - Gooseandra
